# This workflow to validates a python package

name: Validate Python Package
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]

jobs:
  load-constants:
    uses: Full-Python/.github/.github/workflows/python-constants.yml@master

  cache-workspace:
    needs: load-constants
    uses: Full-Python/.github/.github/workflows/python-cache-workspace.yml@master
    permissions:
      actions: write
      contents: read
    with:
      python-version: ${{ fromJSON(needs.load-constants.outputs.env_json).PYTHON_VERSION }}

  get-tag:
    needs: [ cache-workspace, load-constants ]
    uses: Full-Python/.github/.github/workflows/python-package-get-tag.yml@master
    permissions:
      actions: read
      contents: write
      statuses: write
    with:
      source-hash: ${{ needs.cache-workspace.outputs.cache-hash }}
      package-name: ${{ vars.PACKAGE_NAME }}
      tag-regex: ${{ fromJSON(needs.load-constants.outputs.env_json).TAG_REGEX }}
      workflow: ${{ github.workflow }}
      version-hard-fail: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  test-package:
    needs: [ cache-workspace, get-tag ]
    uses: Full-Python/.github/.github/workflows/python-test-package.yml@master
    permissions:
      actions: write
      statuses: write
    with:
      source-hash: ${{ needs.cache-workspace.outputs.cache-hash }}
      workflow: ${{ github.workflow }}
      coverage-requirement: ${{ vars.COVERAGE_REQUIREMENT }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
